{
	"openapi": "3.0.0",
	"components": {
		"examples": {},
		"headers": {},
		"parameters": {},
		"requestBodies": {},
		"responses": {},
		"schemas": {
			"TutorRequestDto": {
				"properties": {
					"name": {
						"type": "string"
					},
					"telefone": {
						"type": "string"
					},
					"email": {
						"type": "string"
					},
					"cidade": {
						"type": "string"
					},
					"bairro": {
						"type": "string"
					},
					"rua": {
						"type": "string"
					},
					"numero": {
						"type": "number",
						"format": "double"
					}
				},
				"required": [
					"name",
					"telefone",
					"email",
					"cidade",
					"bairro",
					"rua",
					"numero"
				],
				"type": "object",
				"additionalProperties": false
			},
			"BasicResponseDto": {
				"properties": {
					"message": {
						"type": "string"
					},
					"object": {}
				},
				"required": [
					"message",
					"object"
				],
				"type": "object",
				"additionalProperties": false
			},
			"TutorDto": {
				"properties": {
					"id": {
						"type": "number",
						"format": "double"
					},
					"name": {
						"type": "string"
					},
					"telefone": {
						"type": "string"
					},
					"email": {
						"type": "string"
					},
					"cidade": {
						"type": "string"
					},
					"bairro": {
						"type": "string"
					},
					"rua": {
						"type": "string"
					},
					"numero": {
						"type": "number",
						"format": "double"
					}
				},
				"required": [
					"id",
					"name",
					"telefone",
					"email",
					"cidade",
					"bairro",
					"rua",
					"numero"
				],
				"type": "object",
				"additionalProperties": false
			},
			"PetRequestDto": {
				"properties": {
					"name": {
						"type": "string"
					},
					"idade": {
						"type": "number",
						"format": "double"
					},
					"tutorID": {
						"type": "number",
						"format": "double"
					},
					"peso": {
						"type": "number",
						"format": "double"
					},
					"raca": {
						"type": "string"
					}
				},
				"required": [
					"name",
					"idade",
					"tutorID",
					"peso",
					"raca"
				],
				"type": "object",
				"additionalProperties": false
			},
			"PetDto": {
				"properties": {
					"id": {
						"type": "number",
						"format": "double"
					},
					"name": {
						"type": "string"
					},
					"idade": {
						"type": "number",
						"format": "double"
					},
					"tutorID": {
						"type": "number",
						"format": "double"
					},
					"peso": {
						"type": "number",
						"format": "double"
					},
					"raca": {
						"type": "string"
					}
				},
				"required": [
					"id",
					"name",
					"idade",
					"tutorID",
					"peso",
					"raca"
				],
				"type": "object",
				"additionalProperties": false
			},
			"FichaRequestDto": {
				"properties": {
					"petID": {
						"type": "number",
						"format": "double"
					},
					"relatorio": {
						"type": "string"
					},
					"data_hora": {
						"type": "string"
					}
				},
				"required": [
					"petID",
					"relatorio",
					"data_hora"
				],
				"type": "object",
				"additionalProperties": false
			},
			"FichaDto": {
				"properties": {
					"id": {
						"type": "number",
						"format": "double"
					},
					"petID": {
						"type": "number",
						"format": "double"
					},
					"relatorio": {
						"type": "string"
					},
					"data_hora": {
						"type": "string"
					}
				},
				"required": [
					"id",
					"petID",
					"relatorio",
					"data_hora"
				],
				"type": "object",
				"additionalProperties": false
			}
		},
		"securitySchemes": {}
	},
	"info": {
		"title": "API Documentação",
		"version": "1.0.0",
		"description": "Documentação da API usando Swagger"
	},
	"paths": {
		"/tutor": {
			"post": {
				"operationId": "CadastrarTutor",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"201": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					}
				},
				"tags": [
					"Tutor"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/TutorRequestDto"
							},
							"example": {
								"name": "Flavita",
								"telefone": "555-666",
								"email": "flavita@email.com",
								"cidade": "Boitucity",
								"bairro": "Boitu-Vera",
								"rua": "Boitu-rua",
								"numero": 27
							}
						}
					}
				}
			},
			"put": {
				"operationId": "AtualizarTutor",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"201": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					}
				},
				"tags": [
					"Tutor"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/TutorDto"
							},
							"example": {
								"id": 1,
								"name": "Flavita",
								"telefone": "555-666",
								"email": "flavita@email.com",
								"cidade": "Boitucity",
								"bairro": "Boitu-Vera",
								"rua": "Boitu-rua",
								"numero": 27
							}
						}
					}
				}
			},
			"delete": {
				"operationId": "DeletarTutor",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"201": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					}
				},
				"tags": [
					"Tutor"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/TutorDto"
							},
							"example": {
								"id": 1,
								"name": "Flavita",
								"telefone": "555-666",
								"email": "flavita@email.com",
								"cidade": "Boitucity",
								"bairro": "Boitu-Vera",
								"rua": "Boitu-rua",
								"numero": 27
							}
						}
					}
				}
			}
		},
		"/tutor/all": {
			"get": {
				"operationId": "ListarTodosTutors",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"201": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					}
				},
				"tags": [
					"Tutor"
				],
				"security": [],
				"parameters": []
			}
		},
		"/pet": {
			"post": {
				"operationId": "CadastrarPet",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"201": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					}
				},
				"tags": [
					"Pet"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/PetRequestDto"
							},
							"example": {
								"name": "Linux",
								"idade": 10,
								"tutorID": 1,
								"peso": 8,
								"raca": "Vira-lata"
							}
						}
					}
				}
			},
			"put": {
				"operationId": "AtualizarPet",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"201": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					}
				},
				"tags": [
					"Pet"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/PetDto"
							},
							"example": {
								"id": 1,
								"name": "Linux",
								"idade": 9,
								"tutorID": 1,
								"peso": 8,
								"raca": "Vira-lata"
							}
						}
					}
				}
			},
			"delete": {
				"operationId": "DeletarPet",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"201": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					}
				},
				"tags": [
					"Pet"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/PetDto"
							},
							"example": {
								"id": 1,
								"name": "Linux",
								"idade": 9,
								"tutorID": 1,
								"peso": 8,
								"raca": "Vira-lata"
							}
						}
					}
				}
			}
		},
		"/pet/all": {
			"get": {
				"operationId": "ListarTodosPets",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"201": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					}
				},
				"tags": [
					"Pet"
				],
				"security": [],
				"parameters": []
			}
		},
		"/ficha": {
			"post": {
				"operationId": "CadastrarFicha",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"201": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					}
				},
				"tags": [
					"Ficha"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/FichaRequestDto"
							},
							"example": {
								"petID": 1,
								"relatorio": "Ele tá bonzinho",
								"data_hora": "04/08/2024"
							}
						}
					}
				}
			},
			"put": {
				"operationId": "AtualizarFicha",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"201": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					}
				},
				"tags": [
					"Ficha"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/FichaDto"
							},
							"example": {
								"id": 1,
								"petID": 1,
								"relatorio": "Ele tá bonzinho :D",
								"data_hora": "04/08/2024"
							}
						}
					}
				}
			},
			"delete": {
				"operationId": "DeletarFicha",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"201": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					}
				},
				"tags": [
					"Ficha"
				],
				"security": [],
				"parameters": [],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/FichaDto"
							},
							"example": {
								"id": 1,
								"petID": 1,
								"relatorio": "Ele tá bonzinho :D",
								"data_hora": "04/08/2024"
							}
						}
					}
				}
			}
		},
		"/ficha/id/{id}": {
			"get": {
				"operationId": "FiltraFicha",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"201": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					}
				},
				"tags": [
					"Ficha"
				],
				"security": [],
				"parameters": [
					{
						"in": "path",
						"name": "id",
						"required": true,
						"schema": {
							"format": "double",
							"type": "number"
						}
					}
				]
			}
		},
		"/ficha/all": {
			"get": {
				"operationId": "ListarTodosFichas",
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"201": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/BasicResponseDto"
								}
							}
						}
					}
				},
				"tags": [
					"Ficha"
				],
				"security": [],
				"parameters": []
			}
		}
	},
	"servers": [
		{
			"url": "http://localhost:3040/api",
			"description": "Servidor de Desenvolvimento"
		}
	]
}